import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'
import {
  createPlaygroundProcesses,
} from '../../scripts/run-playgrounds.mjs'

describe('playground development processes', () => {
  it('gives both frontends the deployment generated by the backend', () => {
    const processes = createPlaygroundProcesses({
      backendEnvironment: 'VITE_CONVEX_URL=http://127.0.0.1:3212\n',
      inheritedEnvironment: {
        NUXT_PUBLIC_CONVEX_URL: 'http://127.0.0.1:3210',
        VITE_CONVEX_URL: 'http://127.0.0.1:3210',
      },
      pnpm: 'pnpm',
      surface: 'all',
    })

    expect(processes).toEqual([
      expect.objectContaining({
        name: 'backend',
      }),
      expect.objectContaining({
        environment: expect.objectContaining({
          VITE_CONVEX_URL: 'http://127.0.0.1:3212',
        }),
        name: 'vue',
      }),
      expect.objectContaining({
        environment: expect.objectContaining({
          NUXT_PUBLIC_CONVEX_URL: 'http://127.0.0.1:3212',
        }),
        name: 'nuxt',
      }),
    ])
  })

  it('backs every root development command with the shared launcher', async () => {
    const manifest = JSON.parse(await readFile('package.json', 'utf8')) as {
      scripts: Record<string, string>
    }

    expect(manifest.scripts.dev)
      .toBe('pnpm run dev:prepare && node scripts/run-playgrounds.mjs')
    expect(manifest.scripts['dev:backend'])
      .toBe('node scripts/run-playgrounds.mjs backend')
    expect(manifest.scripts['dev:vue'])
      .toBe('node scripts/run-playgrounds.mjs vue')
    expect(manifest.scripts['dev:nuxt'])
      .toBe('node scripts/run-playgrounds.mjs nuxt')
  })
})
